version: '3.8'

services:
  auth-service:
    build: ./auth
    container_name: auth_service
    ports:
      - "8000:8000"
    volumes:
      - ./auth_data:/users_db
    networks:
      - chat-net

  chat-service:
    build: ./chat
    container_name: chat_service
    ports:
      - "8001:8001"
    depends_on:
      - auth-service
    networks:
      - chat-net

  frontend:
    build: ./frontend
    container_name: chat_frontend
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - chat-service
    networks:
      - chat-net

networks:
  chat-net:
    driver: bridge